// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: auth/v1/models.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on UserDirectMembership with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UserDirectMembership) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserDirectMembership with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UserDirectMembershipMultiError, or nil if none found.
func (m *UserDirectMembership) ValidateAll() error {
	return m.validate(true)
}

func (m *UserDirectMembership) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for CollectionId

	// no validation rules for MspId

	// no validation rules for UserId

	if all {
		switch v := interface{}(m.GetPolices()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UserDirectMembershipValidationError{
					field:  "Polices",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UserDirectMembershipValidationError{
					field:  "Polices",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPolices()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UserDirectMembershipValidationError{
				field:  "Polices",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Note

	if len(errors) > 0 {
		return UserDirectMembershipMultiError(errors)
	}

	return nil
}

// UserDirectMembershipMultiError is an error wrapping multiple validation
// errors returned by UserDirectMembership.ValidateAll() if the designated
// constraints aren't met.
type UserDirectMembershipMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserDirectMembershipMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserDirectMembershipMultiError) AllErrors() []error { return m }

// UserDirectMembershipValidationError is the validation error returned by
// UserDirectMembership.Validate if the designated constraints aren't met.
type UserDirectMembershipValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserDirectMembershipValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserDirectMembershipValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserDirectMembershipValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserDirectMembershipValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserDirectMembershipValidationError) ErrorName() string {
	return "UserDirectMembershipValidationError"
}

// Error satisfies the builtin error interface
func (e UserDirectMembershipValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserDirectMembership.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserDirectMembershipValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserDirectMembershipValidationError{}

// Validate checks the field values on Role with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Role) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Role with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in RoleMultiError, or nil if none found.
func (m *Role) ValidateAll() error {
	return m.validate(true)
}

func (m *Role) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for CollectionId

	// no validation rules for RoleId

	if all {
		switch v := interface{}(m.GetPolices()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RoleValidationError{
					field:  "Polices",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RoleValidationError{
					field:  "Polices",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPolices()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RoleValidationError{
				field:  "Polices",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Note

	if len(errors) > 0 {
		return RoleMultiError(errors)
	}

	return nil
}

// RoleMultiError is an error wrapping multiple validation errors returned by
// Role.ValidateAll() if the designated constraints aren't met.
type RoleMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RoleMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RoleMultiError) AllErrors() []error { return m }

// RoleValidationError is the validation error returned by Role.Validate if the
// designated constraints aren't met.
type RoleValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RoleValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RoleValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RoleValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RoleValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RoleValidationError) ErrorName() string { return "RoleValidationError" }

// Error satisfies the builtin error interface
func (e RoleValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRole.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RoleValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RoleValidationError{}

// Validate checks the field values on RoleIDList with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RoleIDList) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RoleIDList with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RoleIDListMultiError, or
// nil if none found.
func (m *RoleIDList) ValidateAll() error {
	return m.validate(true)
}

func (m *RoleIDList) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return RoleIDListMultiError(errors)
	}

	return nil
}

// RoleIDListMultiError is an error wrapping multiple validation errors
// returned by RoleIDList.ValidateAll() if the designated constraints aren't met.
type RoleIDListMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RoleIDListMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RoleIDListMultiError) AllErrors() []error { return m }

// RoleIDListValidationError is the validation error returned by
// RoleIDList.Validate if the designated constraints aren't met.
type RoleIDListValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RoleIDListValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RoleIDListValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RoleIDListValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RoleIDListValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RoleIDListValidationError) ErrorName() string { return "RoleIDListValidationError" }

// Error satisfies the builtin error interface
func (e RoleIDListValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRoleIDList.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RoleIDListValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RoleIDListValidationError{}

// Validate checks the field values on UserCollectionRoles with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UserCollectionRoles) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserCollectionRoles with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UserCollectionRolesMultiError, or nil if none found.
func (m *UserCollectionRoles) ValidateAll() error {
	return m.validate(true)
}

func (m *UserCollectionRoles) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for CollectionId

	// no validation rules for MspId

	// no validation rules for UserId

	// no validation rules for Note

	if len(errors) > 0 {
		return UserCollectionRolesMultiError(errors)
	}

	return nil
}

// UserCollectionRolesMultiError is an error wrapping multiple validation
// errors returned by UserCollectionRoles.ValidateAll() if the designated
// constraints aren't met.
type UserCollectionRolesMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserCollectionRolesMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserCollectionRolesMultiError) AllErrors() []error { return m }

// UserCollectionRolesValidationError is the validation error returned by
// UserCollectionRoles.Validate if the designated constraints aren't met.
type UserCollectionRolesValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserCollectionRolesValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserCollectionRolesValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserCollectionRolesValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserCollectionRolesValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserCollectionRolesValidationError) ErrorName() string {
	return "UserCollectionRolesValidationError"
}

// Error satisfies the builtin error interface
func (e UserCollectionRolesValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserCollectionRoles.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserCollectionRolesValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserCollectionRolesValidationError{}

// Validate checks the field values on UserEmbeddedRoles with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UserEmbeddedRoles) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserEmbeddedRoles with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UserEmbeddedRolesMultiError, or nil if none found.
func (m *UserEmbeddedRoles) ValidateAll() error {
	return m.validate(true)
}

func (m *UserEmbeddedRoles) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for CollectionId

	// no validation rules for MspId

	// no validation rules for UserId

	{
		sorted_keys := make([]string, len(m.GetRoles()))
		i := 0
		for key := range m.GetRoles() {
			sorted_keys[i] = key
			i++
		}
		sort.Slice(sorted_keys, func(i, j int) bool { return sorted_keys[i] < sorted_keys[j] })
		for _, key := range sorted_keys {
			val := m.GetRoles()[key]
			_ = val

			// no validation rules for Roles[key]

			if all {
				switch v := interface{}(val).(type) {
				case interface{ ValidateAll() error }:
					if err := v.ValidateAll(); err != nil {
						errors = append(errors, UserEmbeddedRolesValidationError{
							field:  fmt.Sprintf("Roles[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				case interface{ Validate() error }:
					if err := v.Validate(); err != nil {
						errors = append(errors, UserEmbeddedRolesValidationError{
							field:  fmt.Sprintf("Roles[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				}
			} else if v, ok := interface{}(val).(interface{ Validate() error }); ok {
				if err := v.Validate(); err != nil {
					return UserEmbeddedRolesValidationError{
						field:  fmt.Sprintf("Roles[%v]", key),
						reason: "embedded message failed validation",
						cause:  err,
					}
				}
			}

		}
	}

	if len(errors) > 0 {
		return UserEmbeddedRolesMultiError(errors)
	}

	return nil
}

// UserEmbeddedRolesMultiError is an error wrapping multiple validation errors
// returned by UserEmbeddedRoles.ValidateAll() if the designated constraints
// aren't met.
type UserEmbeddedRolesMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserEmbeddedRolesMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserEmbeddedRolesMultiError) AllErrors() []error { return m }

// UserEmbeddedRolesValidationError is the validation error returned by
// UserEmbeddedRoles.Validate if the designated constraints aren't met.
type UserEmbeddedRolesValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserEmbeddedRolesValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserEmbeddedRolesValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserEmbeddedRolesValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserEmbeddedRolesValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserEmbeddedRolesValidationError) ErrorName() string {
	return "UserEmbeddedRolesValidationError"
}

// Error satisfies the builtin error interface
func (e UserEmbeddedRolesValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserEmbeddedRoles.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserEmbeddedRolesValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserEmbeddedRolesValidationError{}

// Validate checks the field values on Attribute with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Attribute) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Attribute with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AttributeMultiError, or nil
// if none found.
func (m *Attribute) ValidateAll() error {
	return m.validate(true)
}

func (m *Attribute) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for CollectionId

	// no validation rules for MspId

	// no validation rules for Oid

	// no validation rules for Value

	if all {
		switch v := interface{}(m.GetPolices()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AttributeValidationError{
					field:  "Polices",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AttributeValidationError{
					field:  "Polices",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPolices()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AttributeValidationError{
				field:  "Polices",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return AttributeMultiError(errors)
	}

	return nil
}

// AttributeMultiError is an error wrapping multiple validation errors returned
// by Attribute.ValidateAll() if the designated constraints aren't met.
type AttributeMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AttributeMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AttributeMultiError) AllErrors() []error { return m }

// AttributeValidationError is the validation error returned by
// Attribute.Validate if the designated constraints aren't met.
type AttributeValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AttributeValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AttributeValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AttributeValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AttributeValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AttributeValidationError) ErrorName() string { return "AttributeValidationError" }

// Error satisfies the builtin error interface
func (e AttributeValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAttribute.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AttributeValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AttributeValidationError{}
