@startebnf
PrimaryKey = "Object Type", ??, "Collection Id",  {??, "object property"};
SubKey = "SubObject Type", ??,  "Collection Id", ??,  "Object Type", {??, "Object Property"},  {??, "SubObject Property"};
@endebnf
