repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # - id: check-yaml
        # exclude: "lib/es/gen/"
      - id: end-of-file-fixer
        exclude: |
          (?x)^(
          lib/es/gen/.*|
          lib/other/.* |
          lib/other/doc/.*
          )$

      - id: trailing-whitespace
        exclude: |
          (?x)^(
          lib/es/gen/.*|
          lib/other/.* |
          lib/other/doc/.*
          )$

      # - id: mixed-line-ending
      #   args: ['--fix=lf']
      # - id: check-shebang-scripts-are-executable

  # - repo: https://github.com/segmentio/golines
  #   rev: v0.11.0
  #   hooks:
  #     - id: golines

  # - repo: https://github.com/golangci/golangci-lint
  #   rev: v1.55.1
  #   hooks:
  #     - id: golangci-lint
