
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
        exclude: "lib/es/gen/"
    -   id: end-of-file-fixer
        exclude: "lib/es/gen/"

    -   id: trailing-whitespace
        exclude: "lib/es/gen/"
