repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
        exclude: "lib/es/gen/"
      - id: end-of-file-fixer
        exclude: "lib/es/gen/"

      - id: trailing-whitespace
        exclude: "lib/es/gen/"
      # - id: mixed-line-ending
      #   args: ['--fix=lf']


  # - repo: https://github.com/segmentio/golines
  #   rev: v0.11.0
  #   hooks:
  #     - id: golines

  # - repo: https://github.com/golangci/golangci-lint
  #   rev: v1.55.1
  #   hooks:
  #     - id: golangci-lint
