version: 3
dotenv:
  - ".env"
  - "./network/k8s/.env"

includes:
  # network:
  #   taskfile: ./network/Taskfile.yml
  #   dir: ./network
  # k8s:
  #   taskfile: ./network/k8s/Taskfile.yml
  #   dir: ./network/k8Hi

  caliper:
    taskfile: ./caliper/Taskfile.yml
    dir: ./caliper

tasks:
  install:
    desc: |
      Install all the protoc plugins

    cmds:
      - go install ./cmd/protoc-gen-saacs-go

  gen:clean:
    cmds:
      - rm -rf ./lib/go/gen/saacs-cc/*
      - rm -rf ./lib/go/gen/*
      - rm -rf ./lib/es/gen/*

  net:up:
    desc: |
      Start the network

      up:
    cmds:
      - bash -c "cd ./network && ./network.sh up createChannel -ca -s couchdb -c
        mychannel"
      - python ./network/scripts/build_configs.py
      - docker-compose -f ./network/explorer/docker-compose.yaml up -d
      - docker-compose -f ./network/prometheus-grafana/docker-compose.yaml up -d
      - task: cc:deploy:biochain

  net:down:
    desc: |
      Stop the network

    cmds:
      - docker-compose -f ./network/explorer/docker-compose.yaml down -v
      - docker-compose -f ./network/prometheus-grafana/docker-compose.yaml down
        -v
      - bash -c "cd ./network && ./network.sh down"

  net:restart:
    desc: |
      Restart the network

    cmds:
      - task: net:down
      - task: net:up

  cc:reload:
    cmds:
      - go mod tidy
      - task: cc:build
      - task: cc:redeploy

  cc:deploy:
    desc: Deploy saacs-cc to the channel and start the saacs-cc container
    cmds:
      - buf generate
      - for: ["noauth", "noauth-no-sub", "identity", "roles"]
        # cmd: bash -c "echo {{ .ITEM }}"
        cmd:
          bash -c "cd ./network && ./network.sh deployCCAAS -ccn {{ .ITEM }}
          -ccp ../pkg/saacs-cc/ "

  cc:redeploy:
    desc: Deploy Updated saacs-cc containers
    cmds:
      - for: ["noauth", "noauth-no-sub", "identity", "roles"]
        # cmd: bash -c "echo {{ .ITEM }}"
        cmd: bash -c "cd ./network && ./cc_restart/{{ .ITEM }}.sh "

  cc:deploy:biochain:
    desc: Deploy saacs-cc to the channel and start the saacs-cc container
    cmds:
      - buf generate
      - cmd:
          bash -c "cd ./network && ./network.sh deployCCAAS -ccn roles -ccp
          ../pkg/saacs-cc/ "
  cc:redeploy:biochain:
    desc: Deploy saacs-cc to the channel and start the saacs-cc container
    cmd: bash -c "cd ./network && ./cc_restart/roles.sh "

  cc:build:
    cmd: docker build -t nova38/saacs:latest -f ./pkg/saacs-cc/Dockerfile .

  build:cc:push:
    cmds:
      - task: cc:build
      - docker tag nova38/saacs:latest nova38/saacs:latest
      - docker push nova38/saacs:latest

  build:es-stub:
    cmd: cd ./pkg/saacs-es && pnpm run stub

  # build:gen-lint:
  #   cmd: cd ./pkg/web/biochain && pnpm lint-gen:fix

  es:run:
    dir: ./pkg/saacs-es
    cmd: pnpm run api
  build:es:
    dir: ./pkg/saacs-es
    cmd: pnpm run build:es

  deploy:prod:api:
    dir: ./pkg/web
    env:
      vars:
        NUXT_API_URL: "https://api-biochain.ittc.ku.edu"
    cmds:
      - pnpm exec nuxi cleanup
      - pnpm run build:prod
      - ssh wisdom  "rm -rf /home/t312a008/projects/server/*"
      # - scp -r .output/* wisdom:/home/t312a008/projects/server

  deploy:prod:static:
    dir: ./pkg/web
    env:
      vars:
        NUXT_API_URL: https://api-biochain.ittc.ku.edu

    cmds:
      - pnpm exec nuxi cleanup
      - pnpm run build:prod-static
      - ssh wisdom  "rm -rf /projects/biochain/website/*"
      - scp -r .output/public/ wisdom:/projects/biochain/website/

  # go:format:
  #   cmds:
  #     - golines --ignore-generated  . -w

  # fabric:getMetadata:
  #   cmds:
  #     - bash -c "cd network && peer saacs-cc query -C default -n Thesis -c
  #       '{"Args":["org.hyperledger.fabric:GetMetadata"]}' "

  default:
    sources:
      - "proto/**/*"
      # - "tools/**/*"
      - "buf.gen.yaml"
    cmds:
      - buf build -o ./cmd/protoc-gen-saacs-es/src/image.bin
      - buf generate
      - task: build:es
      # - task: build:gen-lint
