version: 3
dotenv:
  - ""

tasks:
  install:
    cmds:
#      - go install ./tools/cmd/protoc-gen-cckey
      - go install ./tools/cmd/protoc-gen-go-hlf
  gen:cmd:
    deps:
      - install
    cmds:
      - buf generate
  gen:
    watch: true
    # sources:
    #   - "./lib/proto/rbac/rbac.proto"
    cmds:
      - buf generate

  gen-lib:
    vars:
      template: buf-lib-gen.yaml
    cmds:
      - buf generate --template "${template}"

  go:format:
    cmds:
      - golines --ignore-generated  . -w


  default:
    watch: true
    sources:
      - "proto/**/*"
      - "tools/**/*"
    cmds:
      - buf generate
