version: 3
dotenv:
  - ""

tasks:
  install:
    cmds:
#      - go install ./tools/cmd/protoc-gen-cckey
      - go install ./tools/cmd/protoc-gen-go-hlf
  gen:cmd:
    deps:
      - install
    cmds:
      - buf generate
  gen:all:
    watch: true
    # sources:
    #   - "./lib/proto/rbac/rbac.proto"
    cmds:
      - buf generate

  gen:clean:
    cmds:
      - rm -rf ./lib/go/gen/chaincode/*
      - rm -rf ./lib/go/gen/*
      - rm -rf ./lib/es/gen/*
      - rm -rf ./apps/api/lib/gen/*


  gen-lib:
    vars:
      template: buf-lib-gen.yaml
    cmds:
      - buf generate --template "${template}"

  go:format:
    cmds:
      - golines --ignore-generated  . -w
  go:vendor:
    dir: ./apps/chaincode/auth/noauth
    cmds:
      - go mod vendor

  go:RunSample:
    cmd: go run ./apps/chaincode/sample


  build:chaincode: 
    cmds:
      - go build -o ./apps/chaincode/sample/sample ./apps/chaincode/sample
      - GOOS=linux go build  -gcflags="all=-N -l" -o noauth

  fabric:getMetadata:
    cmds:
      - peer chaincode query -C default -n Thesis -c '{"Args":["org.hyperledger.fabric:GetMetadata"]}'


  network:up:
    cmds:
      - wsl bash -c "./network/network.sh up createChannel -ca -s couchdb -c mychannel"
      # - docker-compose -f ./network/explorer/docker-compose.yaml up -d
      - docker-compose -f ./network/prometheus-grafana/docker-compose.yaml up -d
      # - ./network.sh deployCC -ccn Thesis -ccp ./apps/chaincode/sample -ccl go -ccep "OR('Org1MSP.peer','Org2MSP.peer')" -cccg ./apps/chaincode/sample/collections_config.json
  network:down:
    cmds:
      - wsl bash -c "./network/network.sh down"

  # network:extract:
  #   cmds: 
  #     # - wsl bash -c "find \'$base_path\' -type d -name \'keystore\' -exec find {} -maxdepth 1 -type f \; -exec echo \'Found file: {}\" \;"



  default:
    watch: true
    sources:
      - "proto/**/*"
      - "tools/**/*"
    cmds:
      - buf generate

# ./network.sh cc query -c mychannel -ccn noauth_v0 -ccqc '{"Args":["org.hyperledger.fabric:GetMetadata"]}'
