version: 3
dotenv:
  - ""

tasks:
  install:
    cmds:
      - go install ./tools/cmd/protoc-gen-cckey
      - go install ./tools/cmd/protoc-gen-go-hlf
  gen:
    watch: true
    # sources:
    #   - "./lib/proto/rbac/rbac.proto"
    cmds:
      - buf generate

  gen-lib:
    vars:
      template: buf-lib-gen.yaml
    cmds:
      - buf generate --template "${template}"

  default:
    watch: true
    sources:
      - "lib/**/*"
    cmds:
      - buf generate


