// @generated by protoc-gen-es v1.3.1 with parameter "target=ts"
// @generated from file schema/defs.proto (syntax proto2)
/* eslint-disable */
// @ts-nocheck

import { proto2 } from "@bufbuild/protobuf";

/**
 * @generated from enum TransactionType
 */
export enum TransactionType {
  /**
   * @generated from enum value: INVOKE = 0;
   */
  INVOKE = 0,

  /**
   * @generated from enum value: QUERY = 1;
   */
  QUERY = 1,
}
// Retrieve enum metadata with: proto2.getEnumType(TransactionType)
proto2.util.setEnumType(TransactionType, "TransactionType", [
  { no: 0, name: "INVOKE" },
  { no: 1, name: "QUERY" },
]);
