// @generated by protoc-gen-es v1.3.1 with parameter "target=ts"
// @generated from file schema/service.proto (package schema, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { Collection, Collection_Id, Role, Specimen, Specimen_Georeference, Specimen_HiddenTx, Specimen_Id, Specimen_Image, Specimen_Primary, Specimen_Secondary, Specimen_Taxon, SuggestedUpdate, SuggestedUpdate_Id, User, User_Id } from "./state_pb.js";

/**
 * @generated from enum schema.Permission
 */
export enum Permission {
  /**
   * @generated from enum value: PERMISSION_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: PERMISSION_READ = 1;
   */
  READ = 1,

  /**
   * @generated from enum value: PERMISSION_WRITE = 2;
   */
  WRITE = 2,

  /**
   * @generated from enum value: PERMISSION_ADMIN = 3;
   */
  ADMIN = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(Permission)
proto3.util.setEnumType(Permission, "schema.Permission", [
  { no: 0, name: "PERMISSION_UNSPECIFIED" },
  { no: 1, name: "PERMISSION_READ" },
  { no: 2, name: "PERMISSION_WRITE" },
  { no: 3, name: "PERMISSION_ADMIN" },
]);

/**
 * @generated from message schema.Permissions
 */
export class Permissions extends Message<Permissions> {
  /**
   * @generated from field: bool roles = 1;
   */
  roles = false;

  /**
   * @generated from field: bool role_permissions = 2;
   */
  rolePermissions = false;

  /**
   * @generated from field: bool users = 3;
   */
  users = false;

  /**
   * @generated from field: bool specimen = 4;
   */
  specimen = false;

  /**
   * @generated from field: bool primary = 5;
   */
  primary = false;

  /**
   * @generated from field: bool secondary = 6;
   */
  secondary = false;

  /**
   * @generated from field: bool taxon = 7;
   */
  taxon = false;

  /**
   * @generated from field: bool georeference = 8;
   */
  georeference = false;

  /**
   * @generated from field: bool images = 9;
   */
  images = false;

  /**
   * @generated from field: bool loans = 10;
   */
  loans = false;

  /**
   * @generated from field: bool grants = 11;
   */
  grants = false;

  /**
   * @generated from field: bool hidden = 12;
   */
  hidden = false;

  constructor(data?: PartialMessage<Permissions>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "schema.Permissions";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "roles", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "role_permissions", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 3, name: "users", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 4, name: "specimen", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 5, name: "primary", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 6, name: "secondary", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 7, name: "taxon", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 8, name: "georeference", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 9, name: "images", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 10, name: "loans", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 11, name: "grants", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 12, name: "hidden", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Permissions {
    return new Permissions().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Permissions {
    return new Permissions().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Permissions {
    return new Permissions().fromJsonString(jsonString, options);
  }

  static equals(a: Permissions | PlainMessage<Permissions> | undefined, b: Permissions | PlainMessage<Permissions> | undefined): boolean {
    return proto3.util.equals(Permissions, a, b);
  }
}

/**
 * @generated from message schema.GetSuggestedUpdateRequest
 */
export class GetSuggestedUpdateRequest extends Message<GetSuggestedUpdateRequest> {
  /**
   * @generated from field: schema.SuggestedUpdate.Id id = 1;
   */
  id?: SuggestedUpdate_Id;

  constructor(data?: PartialMessage<GetSuggestedUpdateRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "schema.GetSuggestedUpdateRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "message", T: SuggestedUpdate_Id },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetSuggestedUpdateRequest {
    return new GetSuggestedUpdateRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetSuggestedUpdateRequest {
    return new GetSuggestedUpdateRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetSuggestedUpdateRequest {
    return new GetSuggestedUpdateRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetSuggestedUpdateRequest | PlainMessage<GetSuggestedUpdateRequest> | undefined, b: GetSuggestedUpdateRequest | PlainMessage<GetSuggestedUpdateRequest> | undefined): boolean {
    return proto3.util.equals(GetSuggestedUpdateRequest, a, b);
  }
}

/**
 * @generated from message schema.GetSuggestedUpdateBySpecimenRequest
 */
export class GetSuggestedUpdateBySpecimenRequest extends Message<GetSuggestedUpdateBySpecimenRequest> {
  /**
   * @generated from field: schema.Specimen.Id id = 1;
   */
  id?: Specimen_Id;

  constructor(data?: PartialMessage<GetSuggestedUpdateBySpecimenRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "schema.GetSuggestedUpdateBySpecimenRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "message", T: Specimen_Id },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetSuggestedUpdateBySpecimenRequest {
    return new GetSuggestedUpdateBySpecimenRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetSuggestedUpdateBySpecimenRequest {
    return new GetSuggestedUpdateBySpecimenRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetSuggestedUpdateBySpecimenRequest {
    return new GetSuggestedUpdateBySpecimenRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetSuggestedUpdateBySpecimenRequest | PlainMessage<GetSuggestedUpdateBySpecimenRequest> | undefined, b: GetSuggestedUpdateBySpecimenRequest | PlainMessage<GetSuggestedUpdateBySpecimenRequest> | undefined): boolean {
    return proto3.util.equals(GetSuggestedUpdateBySpecimenRequest, a, b);
  }
}

/**
 * @generated from message schema.GetSuggestedUpdateByCollectionRequest
 */
export class GetSuggestedUpdateByCollectionRequest extends Message<GetSuggestedUpdateByCollectionRequest> {
  /**
   * @generated from field: schema.Collection.Id id = 1;
   */
  id?: Collection_Id;

  constructor(data?: PartialMessage<GetSuggestedUpdateByCollectionRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "schema.GetSuggestedUpdateByCollectionRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "message", T: Collection_Id },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetSuggestedUpdateByCollectionRequest {
    return new GetSuggestedUpdateByCollectionRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetSuggestedUpdateByCollectionRequest {
    return new GetSuggestedUpdateByCollectionRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetSuggestedUpdateByCollectionRequest {
    return new GetSuggestedUpdateByCollectionRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetSuggestedUpdateByCollectionRequest | PlainMessage<GetSuggestedUpdateByCollectionRequest> | undefined, b: GetSuggestedUpdateByCollectionRequest | PlainMessage<GetSuggestedUpdateByCollectionRequest> | undefined): boolean {
    return proto3.util.equals(GetSuggestedUpdateByCollectionRequest, a, b);
  }
}

/**
 * @generated from message schema.GetUserListRequest
 */
export class GetUserListRequest extends Message<GetUserListRequest> {
  constructor(data?: PartialMessage<GetUserListRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "schema.GetUserListRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetUserListRequest {
    return new GetUserListRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetUserListRequest {
    return new GetUserListRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetUserListRequest {
    return new GetUserListRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetUserListRequest | PlainMessage<GetUserListRequest> | undefined, b: GetUserListRequest | PlainMessage<GetUserListRequest> | undefined): boolean {
    return proto3.util.equals(GetUserListRequest, a, b);
  }
}

/**
 * @generated from message schema.GetUserListResponse
 */
export class GetUserListResponse extends Message<GetUserListResponse> {
  /**
   * @generated from field: repeated schema.User users = 1;
   */
  users: User[] = [];

  constructor(data?: PartialMessage<GetUserListResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "schema.GetUserListResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "users", kind: "message", T: User, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetUserListResponse {
    return new GetUserListResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetUserListResponse {
    return new GetUserListResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetUserListResponse {
    return new GetUserListResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetUserListResponse | PlainMessage<GetUserListResponse> | undefined, b: GetUserListResponse | PlainMessage<GetUserListResponse> | undefined): boolean {
    return proto3.util.equals(GetUserListResponse, a, b);
  }
}

/**
 * @generated from message schema.GetUserRequest
 */
export class GetUserRequest extends Message<GetUserRequest> {
  /**
   * @generated from field: schema.User.Id id = 1;
   */
  id?: User_Id;

  constructor(data?: PartialMessage<GetUserRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "schema.GetUserRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "message", T: User_Id },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetUserRequest {
    return new GetUserRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetUserRequest {
    return new GetUserRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetUserRequest {
    return new GetUserRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetUserRequest | PlainMessage<GetUserRequest> | undefined, b: GetUserRequest | PlainMessage<GetUserRequest> | undefined): boolean {
    return proto3.util.equals(GetUserRequest, a, b);
  }
}

/**
 * @generated from message schema.GetCollectionRequest
 */
export class GetCollectionRequest extends Message<GetCollectionRequest> {
  /**
   * @generated from field: schema.Collection.Id id = 1;
   */
  id?: Collection_Id;

  constructor(data?: PartialMessage<GetCollectionRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "schema.GetCollectionRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "message", T: Collection_Id },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetCollectionRequest {
    return new GetCollectionRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetCollectionRequest {
    return new GetCollectionRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetCollectionRequest {
    return new GetCollectionRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetCollectionRequest | PlainMessage<GetCollectionRequest> | undefined, b: GetCollectionRequest | PlainMessage<GetCollectionRequest> | undefined): boolean {
    return proto3.util.equals(GetCollectionRequest, a, b);
  }
}

/**
 * @generated from message schema.GetSpecimenRequest
 */
export class GetSpecimenRequest extends Message<GetSpecimenRequest> {
  /**
   * @generated from field: schema.Specimen.Id id = 1;
   */
  id?: Specimen_Id;

  constructor(data?: PartialMessage<GetSpecimenRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "schema.GetSpecimenRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "message", T: Specimen_Id },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetSpecimenRequest {
    return new GetSpecimenRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetSpecimenRequest {
    return new GetSpecimenRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetSpecimenRequest {
    return new GetSpecimenRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetSpecimenRequest | PlainMessage<GetSpecimenRequest> | undefined, b: GetSpecimenRequest | PlainMessage<GetSpecimenRequest> | undefined): boolean {
    return proto3.util.equals(GetSpecimenRequest, a, b);
  }
}

/**
 * @generated from message schema.GetSpecimenHistoryRequest
 */
export class GetSpecimenHistoryRequest extends Message<GetSpecimenHistoryRequest> {
  /**
   * @generated from field: schema.Specimen.Id id = 1;
   */
  id?: Specimen_Id;

  /**
   * @generated from field: bool include_hidden = 2;
   */
  includeHidden = false;

  constructor(data?: PartialMessage<GetSpecimenHistoryRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "schema.GetSpecimenHistoryRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "message", T: Specimen_Id },
    { no: 2, name: "include_hidden", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetSpecimenHistoryRequest {
    return new GetSpecimenHistoryRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetSpecimenHistoryRequest {
    return new GetSpecimenHistoryRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetSpecimenHistoryRequest {
    return new GetSpecimenHistoryRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetSpecimenHistoryRequest | PlainMessage<GetSpecimenHistoryRequest> | undefined, b: GetSpecimenHistoryRequest | PlainMessage<GetSpecimenHistoryRequest> | undefined): boolean {
    return proto3.util.equals(GetSpecimenHistoryRequest, a, b);
  }
}

/**
 * @generated from message schema.GetSpecimenByCollectionRequest
 */
export class GetSpecimenByCollectionRequest extends Message<GetSpecimenByCollectionRequest> {
  /**
   * @generated from field: schema.Collection.Id id = 1;
   */
  id?: Collection_Id;

  constructor(data?: PartialMessage<GetSpecimenByCollectionRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "schema.GetSpecimenByCollectionRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "message", T: Collection_Id },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetSpecimenByCollectionRequest {
    return new GetSpecimenByCollectionRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetSpecimenByCollectionRequest {
    return new GetSpecimenByCollectionRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetSpecimenByCollectionRequest {
    return new GetSpecimenByCollectionRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetSpecimenByCollectionRequest | PlainMessage<GetSpecimenByCollectionRequest> | undefined, b: GetSpecimenByCollectionRequest | PlainMessage<GetSpecimenByCollectionRequest> | undefined): boolean {
    return proto3.util.equals(GetSpecimenByCollectionRequest, a, b);
  }
}

/**
 * @generated from message schema.GetUserByCollectionRequest
 */
export class GetUserByCollectionRequest extends Message<GetUserByCollectionRequest> {
  /**
   * @generated from field: schema.Collection.Id id = 1;
   */
  id?: Collection_Id;

  constructor(data?: PartialMessage<GetUserByCollectionRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "schema.GetUserByCollectionRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "message", T: Collection_Id },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetUserByCollectionRequest {
    return new GetUserByCollectionRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetUserByCollectionRequest {
    return new GetUserByCollectionRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetUserByCollectionRequest {
    return new GetUserByCollectionRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetUserByCollectionRequest | PlainMessage<GetUserByCollectionRequest> | undefined, b: GetUserByCollectionRequest | PlainMessage<GetUserByCollectionRequest> | undefined): boolean {
    return proto3.util.equals(GetUserByCollectionRequest, a, b);
  }
}

/**
 * @generated from message schema.UserRegisterRequest
 */
export class UserRegisterRequest extends Message<UserRegisterRequest> {
  /**
   * @generated from field: string name = 1;
   */
  name = "";

  /**
   * @generated from field: string email = 2;
   */
  email = "";

  /**
   * @generated from field: string affiliation = 3;
   */
  affiliation = "";

  constructor(data?: PartialMessage<UserRegisterRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "schema.UserRegisterRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "affiliation", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UserRegisterRequest {
    return new UserRegisterRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UserRegisterRequest {
    return new UserRegisterRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UserRegisterRequest {
    return new UserRegisterRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UserRegisterRequest | PlainMessage<UserRegisterRequest> | undefined, b: UserRegisterRequest | PlainMessage<UserRegisterRequest> | undefined): boolean {
    return proto3.util.equals(UserRegisterRequest, a, b);
  }
}

/**
 * @generated from message schema.UpdateMembershipRequest
 */
export class UpdateMembershipRequest extends Message<UpdateMembershipRequest> {
  /**
   * @generated from field: schema.User.Id user_id = 1;
   */
  userId?: User_Id;

  /**
   * @generated from field: schema.Collection.Id collection_id = 2;
   */
  collectionId?: Collection_Id;

  /**
   * @generated from field: schema.Role new_role = 3;
   */
  newRole = Role.PUBLIC_UNSPECIFIED;

  constructor(data?: PartialMessage<UpdateMembershipRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "schema.UpdateMembershipRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "message", T: User_Id },
    { no: 2, name: "collection_id", kind: "message", T: Collection_Id },
    { no: 3, name: "new_role", kind: "enum", T: proto3.getEnumType(Role) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateMembershipRequest {
    return new UpdateMembershipRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateMembershipRequest {
    return new UpdateMembershipRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateMembershipRequest {
    return new UpdateMembershipRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateMembershipRequest | PlainMessage<UpdateMembershipRequest> | undefined, b: UpdateMembershipRequest | PlainMessage<UpdateMembershipRequest> | undefined): boolean {
    return proto3.util.equals(UpdateMembershipRequest, a, b);
  }
}

/**
 * @generated from message schema.CollectionCreateRequest
 */
export class CollectionCreateRequest extends Message<CollectionCreateRequest> {
  /**
   * @generated from field: schema.Collection collection = 1;
   */
  collection?: Collection;

  constructor(data?: PartialMessage<CollectionCreateRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "schema.CollectionCreateRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "collection", kind: "message", T: Collection },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CollectionCreateRequest {
    return new CollectionCreateRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CollectionCreateRequest {
    return new CollectionCreateRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CollectionCreateRequest {
    return new CollectionCreateRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CollectionCreateRequest | PlainMessage<CollectionCreateRequest> | undefined, b: CollectionCreateRequest | PlainMessage<CollectionCreateRequest> | undefined): boolean {
    return proto3.util.equals(CollectionCreateRequest, a, b);
  }
}

/**
 * @generated from message schema.CollectionUpdateRequest
 */
export class CollectionUpdateRequest extends Message<CollectionUpdateRequest> {
  /**
   * @generated from field: schema.Collection collection = 1;
   */
  collection?: Collection;

  constructor(data?: PartialMessage<CollectionUpdateRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "schema.CollectionUpdateRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "collection", kind: "message", T: Collection },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CollectionUpdateRequest {
    return new CollectionUpdateRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CollectionUpdateRequest {
    return new CollectionUpdateRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CollectionUpdateRequest {
    return new CollectionUpdateRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CollectionUpdateRequest | PlainMessage<CollectionUpdateRequest> | undefined, b: CollectionUpdateRequest | PlainMessage<CollectionUpdateRequest> | undefined): boolean {
    return proto3.util.equals(CollectionUpdateRequest, a, b);
  }
}

/**
 * @generated from message schema.sTest
 */
export class sTest extends Message<sTest> {
  /**
   * @generated from field: schema.Specimen.Georeference georeference = 5;
   */
  georeference?: Specimen_Georeference;

  constructor(data?: PartialMessage<sTest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "schema.sTest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 5, name: "georeference", kind: "message", T: Specimen_Georeference },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): sTest {
    return new sTest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): sTest {
    return new sTest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): sTest {
    return new sTest().fromJsonString(jsonString, options);
  }

  static equals(a: sTest | PlainMessage<sTest> | undefined, b: sTest | PlainMessage<sTest> | undefined): boolean {
    return proto3.util.equals(sTest, a, b);
  }
}

/**
 * @generated from message schema.SpecimenCreateRequest
 */
export class SpecimenCreateRequest extends Message<SpecimenCreateRequest> {
  /**
   *  Specimen specimen = 1 [(buf.validate.field).required = true];
   *
   * @generated from field: schema.Specimen.Id id = 1;
   */
  id?: Specimen_Id;

  /**
   * @generated from field: schema.Specimen.Taxon taxon = 2;
   */
  taxon?: Specimen_Taxon;

  /**
   * @generated from field: schema.Specimen.Primary primary = 3;
   */
  primary?: Specimen_Primary;

  /**
   * @generated from field: schema.Specimen.Secondary secondary = 4;
   */
  secondary?: Specimen_Secondary;

  /**
   * @generated from field: schema.Specimen.Georeference georeference = 5;
   */
  georeference?: Specimen_Georeference;

  /**
   * @generated from field: map<string, schema.Specimen.Image> images = 7;
   */
  images: { [key: string]: Specimen_Image } = {};

  /**
   * @generated from field: string loans = 8;
   */
  loans = "";

  /**
   * @generated from field: string grants = 9;
   */
  grants = "";

  constructor(data?: PartialMessage<SpecimenCreateRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "schema.SpecimenCreateRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "message", T: Specimen_Id },
    { no: 2, name: "taxon", kind: "message", T: Specimen_Taxon },
    { no: 3, name: "primary", kind: "message", T: Specimen_Primary },
    { no: 4, name: "secondary", kind: "message", T: Specimen_Secondary },
    { no: 5, name: "georeference", kind: "message", T: Specimen_Georeference },
    { no: 7, name: "images", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "message", T: Specimen_Image} },
    { no: 8, name: "loans", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "grants", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SpecimenCreateRequest {
    return new SpecimenCreateRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SpecimenCreateRequest {
    return new SpecimenCreateRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SpecimenCreateRequest {
    return new SpecimenCreateRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SpecimenCreateRequest | PlainMessage<SpecimenCreateRequest> | undefined, b: SpecimenCreateRequest | PlainMessage<SpecimenCreateRequest> | undefined): boolean {
    return proto3.util.equals(SpecimenCreateRequest, a, b);
  }
}

/**
 * @generated from message schema.SpecimenCreateResponse
 */
export class SpecimenCreateResponse extends Message<SpecimenCreateResponse> {
  /**
   * @generated from field: schema.Specimen specimen = 1;
   */
  specimen?: Specimen;

  constructor(data?: PartialMessage<SpecimenCreateResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "schema.SpecimenCreateResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "specimen", kind: "message", T: Specimen },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SpecimenCreateResponse {
    return new SpecimenCreateResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SpecimenCreateResponse {
    return new SpecimenCreateResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SpecimenCreateResponse {
    return new SpecimenCreateResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SpecimenCreateResponse | PlainMessage<SpecimenCreateResponse> | undefined, b: SpecimenCreateResponse | PlainMessage<SpecimenCreateResponse> | undefined): boolean {
    return proto3.util.equals(SpecimenCreateResponse, a, b);
  }
}

/**
 * @generated from message schema.SpecimenUpdateRequest
 */
export class SpecimenUpdateRequest extends Message<SpecimenUpdateRequest> {
  /**
   * @generated from field: schema.Specimen specimen = 1;
   */
  specimen?: Specimen;

  constructor(data?: PartialMessage<SpecimenUpdateRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "schema.SpecimenUpdateRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "specimen", kind: "message", T: Specimen },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SpecimenUpdateRequest {
    return new SpecimenUpdateRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SpecimenUpdateRequest {
    return new SpecimenUpdateRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SpecimenUpdateRequest {
    return new SpecimenUpdateRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SpecimenUpdateRequest | PlainMessage<SpecimenUpdateRequest> | undefined, b: SpecimenUpdateRequest | PlainMessage<SpecimenUpdateRequest> | undefined): boolean {
    return proto3.util.equals(SpecimenUpdateRequest, a, b);
  }
}

/**
 * @generated from message schema.SpecimenHideTxRequest
 */
export class SpecimenHideTxRequest extends Message<SpecimenHideTxRequest> {
  /**
   * @generated from field: schema.Specimen.Id id = 1;
   */
  id?: Specimen_Id;

  /**
   * @generated from field: schema.Specimen.HiddenTx tx = 2;
   */
  tx?: Specimen_HiddenTx;

  constructor(data?: PartialMessage<SpecimenHideTxRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "schema.SpecimenHideTxRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "message", T: Specimen_Id },
    { no: 2, name: "tx", kind: "message", T: Specimen_HiddenTx },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SpecimenHideTxRequest {
    return new SpecimenHideTxRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SpecimenHideTxRequest {
    return new SpecimenHideTxRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SpecimenHideTxRequest {
    return new SpecimenHideTxRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SpecimenHideTxRequest | PlainMessage<SpecimenHideTxRequest> | undefined, b: SpecimenHideTxRequest | PlainMessage<SpecimenHideTxRequest> | undefined): boolean {
    return proto3.util.equals(SpecimenHideTxRequest, a, b);
  }
}

/**
 * @generated from message schema.SpecimenUnHideTxRequest
 */
export class SpecimenUnHideTxRequest extends Message<SpecimenUnHideTxRequest> {
  /**
   * @generated from field: schema.Specimen.Id id = 1;
   */
  id?: Specimen_Id;

  /**
   * @generated from field: schema.Specimen.HiddenTx tx = 2;
   */
  tx?: Specimen_HiddenTx;

  constructor(data?: PartialMessage<SpecimenUnHideTxRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "schema.SpecimenUnHideTxRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "message", T: Specimen_Id },
    { no: 2, name: "tx", kind: "message", T: Specimen_HiddenTx },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SpecimenUnHideTxRequest {
    return new SpecimenUnHideTxRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SpecimenUnHideTxRequest {
    return new SpecimenUnHideTxRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SpecimenUnHideTxRequest {
    return new SpecimenUnHideTxRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SpecimenUnHideTxRequest | PlainMessage<SpecimenUnHideTxRequest> | undefined, b: SpecimenUnHideTxRequest | PlainMessage<SpecimenUnHideTxRequest> | undefined): boolean {
    return proto3.util.equals(SpecimenUnHideTxRequest, a, b);
  }
}

/**
 * @generated from message schema.SpecimenDeleteRequest
 */
export class SpecimenDeleteRequest extends Message<SpecimenDeleteRequest> {
  /**
   * @generated from field: schema.Specimen.Id id = 1;
   */
  id?: Specimen_Id;

  constructor(data?: PartialMessage<SpecimenDeleteRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "schema.SpecimenDeleteRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "message", T: Specimen_Id },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SpecimenDeleteRequest {
    return new SpecimenDeleteRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SpecimenDeleteRequest {
    return new SpecimenDeleteRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SpecimenDeleteRequest {
    return new SpecimenDeleteRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SpecimenDeleteRequest | PlainMessage<SpecimenDeleteRequest> | undefined, b: SpecimenDeleteRequest | PlainMessage<SpecimenDeleteRequest> | undefined): boolean {
    return proto3.util.equals(SpecimenDeleteRequest, a, b);
  }
}

/**
 * @generated from message schema.SuggestedUpdateCreateRequest
 */
export class SuggestedUpdateCreateRequest extends Message<SuggestedUpdateCreateRequest> {
  /**
   * @generated from field: schema.SuggestedUpdate suggested_update = 1;
   */
  suggestedUpdate?: SuggestedUpdate;

  constructor(data?: PartialMessage<SuggestedUpdateCreateRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "schema.SuggestedUpdateCreateRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "suggested_update", kind: "message", T: SuggestedUpdate },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SuggestedUpdateCreateRequest {
    return new SuggestedUpdateCreateRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SuggestedUpdateCreateRequest {
    return new SuggestedUpdateCreateRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SuggestedUpdateCreateRequest {
    return new SuggestedUpdateCreateRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SuggestedUpdateCreateRequest | PlainMessage<SuggestedUpdateCreateRequest> | undefined, b: SuggestedUpdateCreateRequest | PlainMessage<SuggestedUpdateCreateRequest> | undefined): boolean {
    return proto3.util.equals(SuggestedUpdateCreateRequest, a, b);
  }
}

/**
 * @generated from message schema.SuggestedUpdateApproveRequest
 */
export class SuggestedUpdateApproveRequest extends Message<SuggestedUpdateApproveRequest> {
  /**
   * @generated from field: schema.SuggestedUpdate.Id id = 1;
   */
  id?: SuggestedUpdate_Id;

  /**
   * @generated from field: string comment = 2;
   */
  comment = "";

  constructor(data?: PartialMessage<SuggestedUpdateApproveRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "schema.SuggestedUpdateApproveRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "message", T: SuggestedUpdate_Id },
    { no: 2, name: "comment", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SuggestedUpdateApproveRequest {
    return new SuggestedUpdateApproveRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SuggestedUpdateApproveRequest {
    return new SuggestedUpdateApproveRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SuggestedUpdateApproveRequest {
    return new SuggestedUpdateApproveRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SuggestedUpdateApproveRequest | PlainMessage<SuggestedUpdateApproveRequest> | undefined, b: SuggestedUpdateApproveRequest | PlainMessage<SuggestedUpdateApproveRequest> | undefined): boolean {
    return proto3.util.equals(SuggestedUpdateApproveRequest, a, b);
  }
}

/**
 * @generated from message schema.SuggestedUpdateRejectRequest
 */
export class SuggestedUpdateRejectRequest extends Message<SuggestedUpdateRejectRequest> {
  /**
   * @generated from field: schema.SuggestedUpdate.Id id = 1;
   */
  id?: SuggestedUpdate_Id;

  /**
   * @generated from field: string comment = 2;
   */
  comment = "";

  constructor(data?: PartialMessage<SuggestedUpdateRejectRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "schema.SuggestedUpdateRejectRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "message", T: SuggestedUpdate_Id },
    { no: 2, name: "comment", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SuggestedUpdateRejectRequest {
    return new SuggestedUpdateRejectRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SuggestedUpdateRejectRequest {
    return new SuggestedUpdateRejectRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SuggestedUpdateRejectRequest {
    return new SuggestedUpdateRejectRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SuggestedUpdateRejectRequest | PlainMessage<SuggestedUpdateRejectRequest> | undefined, b: SuggestedUpdateRejectRequest | PlainMessage<SuggestedUpdateRejectRequest> | undefined): boolean {
    return proto3.util.equals(SuggestedUpdateRejectRequest, a, b);
  }
}
