/**
 * @file Automatically generated by barrelsby.
 */

import * as genauthindexts from "./gen/auth/index";
import * as operationswell_knownts from "./operations/well_known";
import * as utilsfactoryts from "./utils/factory";
import * as utilsfakersts from "./utils/fakers";
import * as utilsregistryts from "./utils/registry";
export const gen = {
  auth: {
    index: genauthindexts,
  },
};
export const operations = {
  well_known: operationswell_knownts,
};
export const utils = {
  factory: utilsfactoryts,
  fakers: utilsfakersts,
  registry: utilsregistryts,
};
