/**
 * @file Automatically generated by barrelsby.
 */

import * as genindexts from "./gen/index";
import * as operationswell_knownts from "./operations/well_known";
import * as utilsts from "./utils";

export const utils = utilsts.utils;
export const pb = genindexts;
export const operations = {
  well_known: operationswell_knownts,
};
