// Code generated by proto-gen-go-auth_pb. DO NOT EDIT.
// versions:
// - protoc-gen-cckey v0.0.1
// source: saacs/chaincode/v0/utils.proto

package v0

import (
	fmt "fmt"
	v0 "github.com/nova38/saacs/pkg/saacs-protos/saacs/common/v0"
)

// Service UtilsService
type UtilsServiceInterface[T any] interface {
	// GetCurrentUser
	//
	// # Operation:
	//   - Domain: ACTION_VIEW
	GetCurrentUser(ctx T, req *GetCurrentUserRequest) (res *GetCurrentUserResponse, err error)

	// Bootstrap
	//
	// # Operation:
	//   - Domain: ACTION_UTILITY
	Bootstrap(ctx T, req *BootstrapRequest) (res *BootstrapResponse, err error)

	// AuthorizeOperation
	//
	// # Operation:
	//   - Domain: ACTION_UTILITY
	AuthorizeOperation(ctx T, req *AuthorizeOperationRequest) (res *AuthorizeOperationResponse, err error)

	// GetCollectionsList
	//
	// # Operation:
	//   - Domain: ACTION_VIEW
	GetCollectionsList(ctx T, req *GetCollectionsListRequest) (res *GetCollectionsListResponse, err error)
}

type UtilsServiceBase struct {
}

func (s *UtilsServiceBase) GetEvaluateTransactions() []string {
	return []string{
		"GetCurrentUser",
		"GetCollectionsList",
	}
}

func UtilsServiceGetTxOperation(txName string) (op *v0.Operation, err error) {
	switch txName {
	case "GetCurrentUser":
		// action:ACTION_VIEW
		return &v0.Operation{
			Action: 10,
		}, nil
	case "Bootstrap":
		// action:ACTION_UTILITY
		return &v0.Operation{
			Action: 1,
		}, nil
	case "AuthorizeOperation":
		// action:ACTION_UTILITY
		return &v0.Operation{
			Action: 1,
		}, nil
	case "GetCollectionsList":
		// action:ACTION_VIEW
		return &v0.Operation{
			Action: 10,
		}, nil
	default:
		return nil, fmt.Errorf("No operation defined for " + txName)
	}
	return nil, nil
}

func (s *UtilsServiceBase) GetIgnoredFunctions() []string {
	return []string{"GetTxOperation"}
}
