/**
 * @file Automatically generated by barrelsby.
 */

import * as genauthv1auth_keyts from "./gen/auth/v1/auth_key";
import * as genauthv1auth_pbts from "./gen/auth/v1/auth_pb";
import * as genauthv1auth_regts from "./gen/auth/v1/auth_reg";
import * as genchaincodeauthcommongeneric_gatewayts from "./gen/chaincode/auth/common/generic_gateway";
import * as genchaincodeauthcommongeneric_keyts from "./gen/chaincode/auth/common/generic_key";
import * as genchaincodeauthcommongeneric_pbts from "./gen/chaincode/auth/common/generic_pb";
import * as genchaincodeauthcommongeneric_regts from "./gen/chaincode/auth/common/generic_reg";
import * as genchaincodeauthcommonhelper_regts from "./gen/chaincode/auth/common/helper_reg";
import * as genchaincodeauthrbacschemav1rbac_regts from "./gen/chaincode/auth/rbac/schema/v1/rbac_reg";
import * as genchaincodeccbioschemav0service_gatewayts from "./gen/chaincode/ccbio/schema/v0/service_gateway";
import * as genchaincodeccbioschemav0service_keyts from "./gen/chaincode/ccbio/schema/v0/service_key";
import * as genchaincodeccbioschemav0service_pbts from "./gen/chaincode/ccbio/schema/v0/service_pb";
import * as genchaincodeccbioschemav0service_regts from "./gen/chaincode/ccbio/schema/v0/service_reg";
import * as genchaincodeccbioschemav0state_keyts from "./gen/chaincode/ccbio/schema/v0/state_key";
import * as genchaincodeccbioschemav0state_pbts from "./gen/chaincode/ccbio/schema/v0/state_pb";
import * as genchaincodeccbioschemav0state_regts from "./gen/chaincode/ccbio/schema/v0/state_reg";
import * as genchaincodesamplev0items_keyts from "./gen/chaincode/sample/v0/items_key";
import * as genchaincodesamplev0items_pbts from "./gen/chaincode/sample/v0/items_pb";
import * as genchaincodesamplev0items_regts from "./gen/chaincode/sample/v0/items_reg";
import * as operationswell_knownts from "./operations/well_known";
import * as utilsfactoryts from "./utils/factory";
import * as utilsfakersts from "./utils/fakers";
import * as utilsregistryts from "./utils/registry";
export const gen = {
  auth: {
    v1: {
      auth_key: genauthv1auth_keyts,
      auth_pb: genauthv1auth_pbts,
      auth_reg: genauthv1auth_regts,
    },
  },
  chaincode: {
    auth: {
      common: {
        generic_gateway: genchaincodeauthcommongeneric_gatewayts,
        generic_key: genchaincodeauthcommongeneric_keyts,
        generic_pb: genchaincodeauthcommongeneric_pbts,
        generic_reg: genchaincodeauthcommongeneric_regts,
        helper_reg: genchaincodeauthcommonhelper_regts,
      },
      rbac: {
        schema: {
          v1: {
            rbac_reg: genchaincodeauthrbacschemav1rbac_regts,
          },
        },
      },
    },
    ccbio: {
      schema: {
        v0: {
          service_gateway: genchaincodeccbioschemav0service_gatewayts,
          service_key: genchaincodeccbioschemav0service_keyts,
          service_pb: genchaincodeccbioschemav0service_pbts,
          service_reg: genchaincodeccbioschemav0service_regts,
          state_key: genchaincodeccbioschemav0state_keyts,
          state_pb: genchaincodeccbioschemav0state_pbts,
          state_reg: genchaincodeccbioschemav0state_regts,
        },
      },
    },
    sample: {
      v0: {
        items_key: genchaincodesamplev0items_keyts,
        items_pb: genchaincodesamplev0items_pbts,
        items_reg: genchaincodesamplev0items_regts,
      },
    },
  },
};
export const operations = {
  well_known: operationswell_knownts,
};
export const utils = {
  factory: utilsfactoryts,
  fakers: utilsfakersts,
  registry: utilsregistryts,
};
