apiVersion: monitoring.coreos.com/v1
kind: ScrapeConfig
metadata:
  name: static-config
  namespace: monitoring
  labels:
    prometheus: system-monitoring-prometheus
spec:
  staticConfigs:
    - job_name: "org1-ca"
      static_configs:
        - targets: [ "org1-ca.localho.st:8125" ]
