// Code generated by protoc-gen-go-hlf. DO NOT EDIT.
// versions:
// - protoc-gen-cckey v0.0.1
// source: saacs/auth/v0/roles.proto

package v0

import (
	v0 "github.com/nova38/saacs/pkg/saacs-protos/saacs/common/v0"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	strings "strings"
)

// ──────────────────────────────────────────────────
// saacs.auth.v0.Role
// Primary Item

// Domain Item
func (m *Role) SetKey(key *v0.ItemKey) {
	m.SetKeyAttr(key.ItemKeyParts)
	m.CollectionId = key.GetCollectionId()
	return
}

// SetKeyAttr - Sets the key attributes, returns the number of extra attributes
func (m *Role) SetKeyAttr(attr []string) int {
	if len(attr) > 0 {
		m.RoleId = attr[0]
	} else {
		return 0
	}
	return len(attr) - 1
}

func (m *Role) ItemKey() *v0.ItemKey {
	key := &v0.ItemKey{
		CollectionId: m.GetCollectionId(),
		ItemKind:     2,
		ItemType:     "saacs.auth.v0.Role",
		ItemKeyParts: m.KeyAttr(),
	}
	return key
}

func (m *Role) KeyAttr() []string {
	attr := []string{}
	attr = append(attr, m.GetRoleId())
	return attr
}

func (m *Role) ItemKind() v0.ItemKind {
	return v0.ItemKind_ITEM_KIND_PRIMARY_ITEM
}

func (m *Role) ItemType() string {
	return "saacs.auth.v0.Role"
}

func (m *Role) KeySchema() *v0.KeySchema {
	return &v0.KeySchema{
		ItemKind:   v0.ItemKind_ITEM_KIND_PRIMARY_ITEM,
		Properties: &fieldmaskpb.FieldMask{Paths: []string{"role_id"}},
	}
}

// NewFromKey - Creates a new item from a key
func (m *Role) NewFromKey(key *v0.ItemKey) *Role {
	item := &Role{}
	item.SetKey(key)

	return item
}

// StateKey - Returns a composite key for the state
// This follows the same structure as the saacs-cc stub library,
// Main difference is that it doesn't check the key for invalid characters
//
// Example key:= "\u0000auth.Collection\u0000collection0\u0000collection0\u0000"

func (m *Role) StateKey() string {

	const sep = string(rune(0))

	attrs := m.ItemKey().GetItemKeyParts()
	if attrs == nil {
		panic("ItemKeyParts is nil")
	}

	collectionId := m.ItemKey().GetCollectionId()
	if collectionId == "" {
		panic("CollectionId is nil")
	}

	if len(attrs) == 0 {
		k := sep + "saacs.auth.v0.Role" + sep + collectionId + sep
		return k
	}
	k := sep + "saacs.auth.v0.Role" + sep + collectionId + sep + strings.Join(attrs, sep) + sep

	return k
}

// ──────────────────────────────────────────────────
// saacs.auth.v0.UserCollectionRoles
// Primary Item

// Domain Item
func (m *UserCollectionRoles) SetKey(key *v0.ItemKey) {
	m.SetKeyAttr(key.ItemKeyParts)
	m.CollectionId = key.GetCollectionId()
	return
}

// SetKeyAttr - Sets the key attributes, returns the number of extra attributes
func (m *UserCollectionRoles) SetKeyAttr(attr []string) int {
	if len(attr) > 0 {
		m.MspId = attr[0]
	} else {
		return 0
	}
	if len(attr) > 1 {
		m.UserId = attr[1]
	} else {
		return 0
	}
	return len(attr) - 2
}

func (m *UserCollectionRoles) ItemKey() *v0.ItemKey {
	key := &v0.ItemKey{
		CollectionId: m.GetCollectionId(),
		ItemKind:     2,
		ItemType:     "saacs.auth.v0.UserCollectionRoles",
		ItemKeyParts: m.KeyAttr(),
	}
	return key
}

func (m *UserCollectionRoles) KeyAttr() []string {
	attr := []string{}
	attr = append(attr, m.GetMspId())
	attr = append(attr, m.GetUserId())
	return attr
}

func (m *UserCollectionRoles) ItemKind() v0.ItemKind {
	return v0.ItemKind_ITEM_KIND_PRIMARY_ITEM
}

func (m *UserCollectionRoles) ItemType() string {
	return "saacs.auth.v0.UserCollectionRoles"
}

func (m *UserCollectionRoles) KeySchema() *v0.KeySchema {
	return &v0.KeySchema{
		ItemKind: v0.ItemKind_ITEM_KIND_PRIMARY_ITEM,
		Properties: &fieldmaskpb.FieldMask{Paths: []string{
			"msp_id",
			"user_id",
		}},
	}
}

// NewFromKey - Creates a new item from a key
func (m *UserCollectionRoles) NewFromKey(key *v0.ItemKey) *UserCollectionRoles {
	item := &UserCollectionRoles{}
	item.SetKey(key)

	return item
}

// StateKey - Returns a composite key for the state
// This follows the same structure as the saacs-cc stub library,
// Main difference is that it doesn't check the key for invalid characters
//
// Example key:= "\u0000auth.Collection\u0000collection0\u0000collection0\u0000"

func (m *UserCollectionRoles) StateKey() string {

	const sep = string(rune(0))

	attrs := m.ItemKey().GetItemKeyParts()
	if attrs == nil {
		panic("ItemKeyParts is nil")
	}

	collectionId := m.ItemKey().GetCollectionId()
	if collectionId == "" {
		panic("CollectionId is nil")
	}

	if len(attrs) == 0 {
		k := sep + "saacs.auth.v0.UserCollectionRoles" + sep + collectionId + sep
		return k
	}
	k := sep + "saacs.auth.v0.UserCollectionRoles" + sep + collectionId + sep + strings.Join(attrs, sep) + sep

	return k
}

// ──────────────────────────────────────────────────
// saacs.auth.v0.UserGlobalRoles
// Primary Item

// Domain Item
func (m *UserGlobalRoles) SetKey(key *v0.ItemKey) {
	m.SetKeyAttr(key.ItemKeyParts)
	m.CollectionId = key.GetCollectionId()
	return
}

// SetKeyAttr - Sets the key attributes, returns the number of extra attributes
func (m *UserGlobalRoles) SetKeyAttr(attr []string) int {
	if len(attr) > 0 {
		m.MspId = attr[0]
	} else {
		return 0
	}
	if len(attr) > 1 {
		m.UserId = attr[1]
	} else {
		return 0
	}
	return len(attr) - 2
}

func (m *UserGlobalRoles) ItemKey() *v0.ItemKey {
	key := &v0.ItemKey{
		CollectionId: m.GetCollectionId(),
		ItemKind:     2,
		ItemType:     "saacs.auth.v0.UserGlobalRoles",
		ItemKeyParts: m.KeyAttr(),
	}
	return key
}

func (m *UserGlobalRoles) KeyAttr() []string {
	attr := []string{}
	attr = append(attr, m.GetMspId())
	attr = append(attr, m.GetUserId())
	return attr
}

func (m *UserGlobalRoles) ItemKind() v0.ItemKind {
	return v0.ItemKind_ITEM_KIND_PRIMARY_ITEM
}

func (m *UserGlobalRoles) ItemType() string {
	return "saacs.auth.v0.UserGlobalRoles"
}

func (m *UserGlobalRoles) KeySchema() *v0.KeySchema {
	return &v0.KeySchema{
		ItemKind: v0.ItemKind_ITEM_KIND_PRIMARY_ITEM,
		Properties: &fieldmaskpb.FieldMask{Paths: []string{
			"msp_id",
			"user_id",
		}},
	}
}

// NewFromKey - Creates a new item from a key
func (m *UserGlobalRoles) NewFromKey(key *v0.ItemKey) *UserGlobalRoles {
	item := &UserGlobalRoles{}
	item.SetKey(key)

	return item
}

// StateKey - Returns a composite key for the state
// This follows the same structure as the saacs-cc stub library,
// Main difference is that it doesn't check the key for invalid characters
//
// Example key:= "\u0000auth.Collection\u0000collection0\u0000collection0\u0000"

func (m *UserGlobalRoles) StateKey() string {

	const sep = string(rune(0))

	attrs := m.ItemKey().GetItemKeyParts()
	if attrs == nil {
		panic("ItemKeyParts is nil")
	}

	collectionId := m.ItemKey().GetCollectionId()
	if collectionId == "" {
		panic("CollectionId is nil")
	}

	if len(attrs) == 0 {
		k := sep + "saacs.auth.v0.UserGlobalRoles" + sep + collectionId + sep
		return k
	}
	k := sep + "saacs.auth.v0.UserGlobalRoles" + sep + collectionId + sep + strings.Join(attrs, sep) + sep

	return k
}
