FROM golang:1.21.4-bookworm AS build-env
# ENV CORE_CHAINCODE_ID_NAME=biochain


WORKDIR /app/chaincode
COPY . .

# CMD ["/bin/bash"]

RUN go build -gcflags="all=-N -l" -o /noauth
RUN ls /go
# RUN go get -d -v ./...
#RUN go install -v

# FROM golang:1.21.4-bookworm AS debug-env

WORKDIR /
# COPY --from=build-env /go/bin/dlv /
# COPY --from=build-env /noauth /

# COPY /go/bin/dlv /
# COPY /noauth /

# RUN ls -la
# RUN go build -o noauth.exe

EXPOSE 9999
EXPOSE 6060
EXPOSE 40000
# # CMD ["/bin/bash"]
# CMD ["/go/bin/dlv", "--listen=:40000", "--headless=true", "--api-version=2", "--accept-multiclient", "exec", " /noauth"]

#
CMD ["/noauth"]
